jQuery(document).ready(function(){
    var scripts = document.getElementsByTagName("script");
    var jsFolder = "";
    for (var i= 0; i< scripts.length; i++)
    {
        if( scripts[i].src && scripts[i].src.match(/initslider-1\.js/i))
            jsFolder = scripts[i].src.substr(0, scripts[i].src.lastIndexOf("/") + 1);
    }
    jQuery("#amazingslider-1").amazingslider({
        sliderid:1,
        jsfolder:jsFolder,
        width:1024,
        height:768,
        skinsfoldername:"",
        loadimageondemand:false,
        videohidecontrols:false,
        watermarktextcss:"font:12px Arial,Tahoma,Helvetica,sans-serif;color:#333;padding:2px 4px;-webkit-border-radius:4px;-moz-border-radius:4px;border-radius:4px;background-color:#fff;opacity:0.9;filter:alpha(opacity=90);",
        watermarkstyle:"text",
        donotresize:true,
        enabletouchswipe:false,
        fullscreen:true,
        autoplayvideo:false,
        addmargin:false,
        watermarklinkcss:"text-decoration:none;font:12px   Arial,Tahoma,Helvetica,sans-serif;color:#333;",
        watermarktext:"",
        watermarklink:"",
        transitiononfirstslide:false,
        forceflash:false,
        isresponsive:true,
        forceflashonie11:false,
        forceflashonie10:false,
        pauseonmouseover:false,
        playvideoonclickthumb:false,
        showwatermark:false,
        slideinterval:4000,
        watermarkpositioncss:"display:block;position:absolute;bottom:4px;right:4px;",
        watermarkimage:"",
        fullwidth:false,
        randomplay:false,
        watermarktarget:"_blank",
        scalemode:"fill",
        loop:0,
        autoplay:true,
        timerheight:2,
        shownumbering:false,
        skin:"Lightbox",
        addgooglefonts:false,
        navpreviewposition:"top",
        navpreviewwidth:120,
        googlefonts:"",
        textpositionmarginright:24,
        lightboxdescriptionbottomcss:"{color:#333; font-size:12px; font-family:Arial,Helvetica,sans-serif; overflow:hidden; text-align:left; margin:4px 0px 0px; padding: 0px;}",
        navthumbnavigationarrowimagewidth:32,
        navcolor:"#999999",
        arrowwidth:36,
        titlecssresponsive:"font-size:12px;",
        texteffect1:"slide",
        texteffect2:"slide",
        ribbonposition:"topleft",
        navthumbdescriptioncss:"display:block;position:relative;padding:2px 4px;text-align:left;font:normal 12px Arial,Helvetica,sans-serif;color:#333;",
        lightboxtitlebottomcss:"{color:#333; font-size:14px; font-family:Armata,sans-serif,Arial; overflow:hidden; text-align:left;}",
        arrowstyle:"always",
        navthumbtitleheight:20,
        navswitchonmouseover:false,
        arrowtop:50,
        textstyle:"dynamic",
        playvideoimageheight:64,
        showbackgroundimage:false,
        customcss:"",
        navshowplaypausestandaloneheight:28,
        shadowcolor:"#aaaaaa",
        textbgcss:"display:none;",
        navdirection:"horizontal",
        navshowplaypausestandalonemarginx:8,
        bottomshadowimagewidth:96,
        navshowpreview:true,
        navmarginy:-32,
        navmarginx:-32,
        textpositionmarginleft:24,
        backgroundimagetop:-10,
        timercolor:"#ffffff",
        navhighlightcolor:"#333333",
        texteffectdelay1:1000,
        texteffectdelay2:1500,
        texteffectduration1:600,
        texteffectduration2:600,
        navbuttoncolor:"#999999",
        texteffectslidedirection:"random",
        showfacebook:true,
        titlecss:"display:table; position:relative; font-weight:300; font-style:italic; font-size:50px; font-family:Georgia,sans-serif,Arial; color:#fff; padding:10px; margin:0px auto;",
        texteffectslidedistance1:60,
        texteffectslidedistance2:60,
        lightboxshowsocial:false,
        lightboxthumbtopmargin:12,
        navfeaturedarrowimageheight:8,
        bordercolor:"#ffffff",
        navthumbtitlewidth:120,
        texteffectseparate:true,
        arrowheight:80,
        bottomshadowimage:"../img/Control/bottomshadow-110-95-1.png",
        lightboxshowdescription:false,
        timerposition:"bottom",
        navthumbnavigationstyle:"arrow",
        borderradius:0,
        lightboxshowfacebook:true,
        texteffecteasing2:"easeOutCubic",
        navthumbstyle:"imageonly",
        showtwitter:true,
        navbordercolor:"#ffffff",
        navpreviewarrowheight:8,
        showbottomshadow:true,
        texteffectslidedistance:3000,
        texteffectdelay:500,
        backgroundimage:"",
        textformat:"Center text",
        navshowbuttons:false,
        navthumbtitlecss:"display:block;position:relative;padding:2px 4px;text-align:left;font:bold 14px Arial,Helvetica,sans-serif;color:#333;",
        ribbonmarginy:0,
        ribbonmarginx:0,
        navbuttonhighlightcolor:"#333333",
        socialmode:"mouseover",
        navpreviewheight:60,
        descriptioncssresponsive:"font-size:12px;",
        navthumbresponsivemode:"samesize",
        lightboxshowtwitter:true,
        navshowplaypause:true,
        navshowplayvideo:false,
        buttoncss:"display:block; position:relative; margin:10px auto;",
        navshowplaypausestandalonemarginy:8,
        navbuttonradius:0,
        navthumbcolumn:5,
        navthumbnavigationarrowimageheight:32,
        navradius:0,
        texteffecteasing1:"easeOutCubic",
        lightboxshownavigation:false,
        showshadow:false,
        navfeaturedarrowimagewidth:16,
        navborderhighlightcolor:"",
        textautohide:true,
        lightboxthumbwidth:80,
        navthumbtitlehovercss:"text-decoration:underline;",
        navthumbmediumheight:64,
        texteffectresponsivesize:600,
        texteffecteasing:"easeOutCubic",
        texteffect:"slide",
        lightboxthumbheight:60,
        navspacing:8,
        navwidth:16,
        navheight:16,
        timeropacity:0.6,
        navshowplaypausestandalone:false,
        navpreviewbordercolor:"#ffffff",
        lightboxthumbbottommargin:8,
        navborder:4,
        navthumbmediumsize:800,
        textpositionmargintop:24,
        buttoncssresponsive:"",
        arrowimage:"../img/Control/arrows-36-80-0.png",
        navfonthighlightcolor:"#666666",
        showpinterest:true,
        navpreviewborder:4,
        navbuttonshowbgimage:true,
        playvideoimagewidth:64,
        navshowpreviewontouch:false,
        showtimer:false,
        navmultirows:false,
        showsocial:false,
        navthumbsmallsize:480,
        showribbon:false,
        navstyle:"bullets",
        descriptioncss:"display:block; position:relative; font-weight:300; font-style:normal; font-size:20px; line-height:30px; font-family:Georgia,sans-serif,Arial; color:#fff; padding:10px; margin:0px auto;",
        numberingformat:"%NUM/%TOTAL ",
        navthumbmediumwidth:64,
        navfontsize:12,
        navimage:"../img/Control/bullet.png",
        navshowplaypausestandaloneautohide:false,
        navshowarrow:true,
        navshowfeaturedarrow:false,
        lightboxbarheight:64,
        ribbonimagey:0,
        ribbonimagex:0,
        navthumbsmallheight:48,
        textpositiondynamic:"centercenter",
        navrowspacing:8,
        navshowplaypausestandaloneposition:"bottomright",
        lightboxshowpinterest:true,
        arrowhideonmouseleave:1000,
        navshowplaypausestandalonewidth:28,
        navthumbresponsive:false,
        navopacity:0.8,
        backgroundimagewidth:120,
        arrowmargin:0,
        texteffectduration:2000,
        border:6,
        navfontcolor:"#333333",
        bottomshadowimagetop:95,
        initsocial:false,
        textpositionstatic:"bottom",
        navthumbsmallcolumn:3,
        textcss:"display:block; padding:48px; text-align:center;",
        navthumbsmallwidth:48,
        navthumbmediumcolumn:4,
        textpositionmarginstatic:0,
        navposition:"bottom",
        texteffectslidedirection1:"right",
        navpreviewarrowwidth:16,
        texteffectslidedirection2:"right",
        texteffectresponsive:true,
        shadowsize:5,
        textpositionmarginbottom:24,
        lightboxshowtitle:true,
        slice: {
            duration:1500,
            easing:"easeOutCubic",
            checked:true,
            effects:"up,down,updown",
            slicecount:10
        },
        blocks: {
            columncount:5,
            checked:true,
            rowcount:5,
            effects:"topleft,bottomright,top,bottom,random",
            duration:1500,
            easing:"easeOutCubic"
        },
        elastic: {
            duration:1000,
            easing:"easeOutElastic",
            checked:true
        },
        threedflipwithzoom: {
            duration:2000,
            fallback:"flipwithzoom",
            checked:true
        },
        threedwithzoom: {
            duration:2500,
            fallback:"flip",
            checked:true
        },
        flip: {
            duration:1500,
            checked:true
        },
        threedflip: {
            duration:1500,
            fallback:"flip",
            checked:true
        },
        threedtiles: {
            duration:2000,
            fallback:"tiles",
            checked:true
        },
        slide: {
            duration:1000,
            easing:"easeOutCubic",
            checked:true
        },
        kenburns: {
            duration:5000,
            checked:true
        },
        threedhorizontalwithzoom: {
            duration:2200,
            fallback:"flipwithzoom",
            checked:true
        },
        shuffle: {
            duration:1500,
            easing:"easeOutCubic",
            columncount:5,
            checked:true,
            rowcount:5
        },
        threedhorizontal: {
            checked:true,
            bgcolor:"#222222",
            perspective:1000,
            slicecount:1,
            duration:1500,
            easing:"easeOutCubic",
            fallback:"slice",
            scatter:5,
            perspectiveorigin:"bottom"
        },
        threed: {
            checked:true,
            bgcolor:"#222222",
            perspective:1000,
            slicecount:5,
            duration:1500,
            easing:"easeOutCubic",
            fallback:"slice",
            scatter:5,
            perspectiveorigin:"right"
        },
        transition:"slice,blocks,elastic,threedflipwithzoom,threedwithzoom,flip,threedflip,threedtiles,slide,kenburns,threedhorizontalwithzoom,shuffle,threedhorizontal,threed",
        scalemode:"fill",
        isfullscreen:true,
        textformat: {
            "Center text": {
                titlecssresponsive:"font-size:50px;",
                descriptioncss:"display:block; position:relative; font-weight:300; font-style:normal; font-size:20px; line-height:30px; font-family:Georgia,sans-serif,Arial; color:#fff; padding:10px; margin:0px auto;",
                texteffect1:"slide",
                texteffect2:"slide",
                descriptioncssresponsive:"font-size:12px;",
                texteffectseparate:true,
                texteffectduration:2000,
                textpositionmarginleft:24,
                textpositionstatic:"bottom",
                buttoncssresponsive:"",
                buttoncss:"display:block; position:relative; margin:10px auto;",
                addgooglefonts:false,
                textpositionmargintop:24,
                texteffecteasing2:"easeOutCubic",
                texteffectdelay:500,
                texteffecteasing1:"easeOutCubic",
                texteffectdelay1:1000,
                texteffectdelay2:1500,
                texteffectduration1:600,
                googlefonts:"",
                textpositionmarginright:24,
                textautohide:true,
                textstyle:"dynamic",
                texteffectslidedistance:300,
                texteffectslidedirection:"random",
                textcss:"display:block; padding:48px; text-align:center;",
                titlecss:"display:table; position:relative; font-weight:300; font-style:italic; font-size:70px; font-family:'Dancing Script', cursive;; color:#f63; padding:10px; margin:0px auto;",
                textpositionmarginstatic:0,
                texteffectresponsivesize:600,
                texteffectslidedirection1:"right",
                texteffectslidedistance1:60,
                texteffectslidedistance2:60,
                texteffectslidedirection2:"right",
                textbgcss:"display:none;",
                texteffectresponsive:true,
                texteffecteasing:"easeOutCubic",
                textpositiondynamic:"centercenter",
                textpositionmarginbottom:24,
                texteffect:"slide",
                texteffectduration2:600
            }
        }
    });
});